
  version: "2.1"

  services:

    ###############################################################
    #    Functions service
    ###############################################################

    functions:
      build:
        context: ./
      volumes:
        - ./example.js:/usr/src/app/example.js

      expose:
        - "8000"

    ###############################################################
    #    StateFun runtime
    ###############################################################

    statefun:
      image: apache/flink-statefun-playground:3.2.0-1.0
      ports:
        - "8081:8081"
        - "8090:8090"
        - "8091:8091"
      depends_on:
        - functions
      volumes:
        - ./module.yaml:/module.yaml
